# Generated by Django 5.1.6 on 2025-02-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='youtube_iframe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
