# Generated by Django 5.1.6 on 2025-03-09 14:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolio_tags_portfolio_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#533fab', image_field=None, max_length=25, samples=None),
        ),
    ]
