# Generated by Django 5.1.6 on 2025-02-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_youtube_iframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='youtube_iframe',
        ),
    ]
