# Generated by Django 5.1.6 on 2025-02-24 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_tag_portfolio_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='tags',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.tag'),
        ),
    ]
